#!/usr/bin/env bash
# Copies a file from the local server to a remote server
if [ $# -lt 3 ]
then
	echo Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
elif [ $# -gt 3 ]
then
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
else
	scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi
