#!/usr/bin/env bash
# Installs nginx and configures it on a remote server
# Where Nginx should be listening on port 80
# Server a page that would return a Hello World string
#
sudo apt-get -y update
sudo apt-get -y install nginx
#
# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
#
# Configures Nginx to serve a Hello World Page
echo "Hello World!" | sudo tee /var/www/html/index.html
#
# Allow nginx to connect over a firewall
sudo ufw allow 'Nginx HTTP'
#
# Start Nginx to apply changes
sudo service nginx restart
