#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#+    at the root with curl GET request.
# Configures /redirect_me as a "301 Moved Permanently".
# Includes a custom 404 page containing "Ceci n'est pas une page".

sudo apt-get update
sudo apt-get install -y nginx

mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo touch /var/www/html/404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

printf %s "server {
    listen 80;
    listen [::]:80 default-server;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://www.youtube.com/watch?v=QH2-TGU1wu4/;
    }

    error_page 404 /404.html;
    location /404 {
        root /var/www/html;
	internal;
    }
}" > /etc/nginx/sites-available/default

sudo service nginx restart
