#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello world!" when queried
#+     at the root with a curl GET request.
# Configures /redirect_me as a "301 Moved Permanently".
# Includes a custom 404 page containing "Ceci n'est pas une page".
# Configures Nginx server with a custom header
sudo apt-get update -y
sudo apt-get install nginx -y
#
# Starting nginx service
sudo service nginx start
#
# Allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'
#
# Configure nginx with a custom header
sudo sed -i '24i\        add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
#
sudo service nginx restart
