#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello world!" when queried
#+     at the root with a curl GET request.
# Configures /redirect_me as a "301 Moved Permanently".
# Includes a custom 404 page containing "Ceci n'est pas une page".
# Configures Nginx server with a custom header
sudo apt-get update -y
sudo apt-get install nginx -y
#
# Starting nginx service
sudo service nginx start
#
# Allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'
#
# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
#
# Creating a new index
echo "Hello World!" | sudo tee /var/www/html/index.html
#
# Setting up /redirect_me to a youtube video
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
# 
# Setting up custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html
sudo sed -i '25i\       error_page /error_404.html;' /etc/nginx/sites-available/default
#
# Configure nginx with a custom header
sudo sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;include \/etc\/nginx\/sites-enabled\/*;\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx/nginx.conf
#
sudo service nginx restart
