#!/usr/bin/env bash
# Installs HAProy version 1.8 with the following configurations:
# Enables management via the init script.
# Distributes requests using a round-robin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAProxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get install -y software-properties-common
sudo add-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get update
sudo apt-get update
sudo apt-get install -y haproxy=2.0.*
sed -i "$ a frontend load_balancer\n	bind *:80\n	mode http\n	default_backend web_server\nbackend web_servers\n	balance roundrobin\n	server 78195-web-02 54.210.28.254:80 check\n	server 78195-web-01 100.26.177.156:80 check " /etc/haproxy.cfg
sudo service haproxy start
