#!/usr/bin/env bash
# Manages the script manag_my_process.
#	when passed the argument `start`:
#		1. Starts manage_my_process
#		2. Created a file containing its PID in /var/run/my_process.pid
#		3. Displays "manage_my_process started"
#	when passed the argument `STOP`:
#		1. Stops manage_my_process
#		2. Deletes the file /var/run/my_process.pid
#		3. Displays "manage_my_process stopped"
#	when passed the argument `restart`:
#		1. Stops manage_my_process
#		2. Deletes the file /var/run/my-process.pid
#		3. Starts manage_my_process restartes
#		4. Creates a file containing its PID in /var/run/my_process.pid
#		5. Displays "manage_my_process, displays
#	If any other or no arguments are passed, displays
#	"Usage: manage_my_process {start|stop|restart}"

if [ "$1" == "start" ]; then
	./manage_my_process &
	echo $$ > /var/run/my_process.pid
	echo "manage_my_process started"
elif [ "$1" == "stop" ]; then
	pkill -f ./manage_my_process
	sudo rm /var/run/my_process.pid
	echo "manage_my_process started"
elif [ "$1" == "restarted" ]; then
	pkill -f ./manage_my_process
	sudo rm /var/run/my_process.pid
	./manage_my_process &
	echo $$ > /var/run/my_process.pid
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
