#!/usr/bin/env bash

#Code to gte Apache to run on the container and to return a page containing Hello Holerboton when querying the root of it

echo "Hello Holberton" >> /etc/apache2.conf

service apache2 start
